### PR TITLE
Updated the README - can I become a owner of the repository?

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**

### CODE REVIEW

**Comment by s4m-mo** [comment]
Hi harry, just checking now. I will grant you admin

**Comment by s4m-mo** [comment]
Don't edit the pages yet, please just work on the TS work, but I will finish it by tomorrow, I am  busy for the next half hour or so before that.

**Comment by Harry-Hopkinson** [comment]
Okay I will just work on the Typescript

**Comment by s4m-mo** [comment]
I will be online again at about half 6, and will finish the pages, so we can start working on them together.

**Comment by Harry-Hopkinson** [comment]
Okay - live share?

**Comment by Harry-Hopkinson** [comment]
What are we doing with the notification system.

**Comment by s4m-mo** [comment]
Check the team chat.

**Comment by Harry-Hopkinson** [comment]
what team chat?

**Comment by s4m-mo** [comment]
Go to our organization > Teams > web-devs  then there will be discussions.

**Pull request merged**
